### ISSUE TITLE
Issue with Bundler during installation

### ISSUE THREAD

**Issue by EchoesNetwork** [inertia186/cobblebot#6]
Hi. I've been trying to install Cobblebot recently, and when I get to the command:
`bundle install`
I receive the following error:

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
The latest bundler is 1.16.1, but you are currently running 1.15.1.
To update, run gem install bundler

```

`Could not locate Gemfile`

When I attempt to update Bundler, it updates successfully, though I still receive the same error where it fails to find the Gemfile. For reference, I'm running Ubuntu artful 17.10. Thanks!

**Comment by inertia186** [comment]
I recommend rvm.io (ruby version manager).  Once installed, you can avoid sudo completely.
